version: '3.9'
services:
  tracker-service:
    image: tracker_image
    container_name: tracker-service
    build: UserTask/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8083:8083
    depends_on:
      - mongoService


  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8086:8086
    depends_on:
      - mysqlService


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  cloudapiservice:
    image: apigateway-service
    build: SpringCloudApiGateway/
    restart: always
    networks:
      - mynetwork
    ports:
      - 9000:9000
    environment:
      API_GATEWAY_PORT: 9000

  eureka-service:
    container_name: containerEureka
    build: EurekaServer/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8761:8761

networks:
  mynetwork:
    driver: bridge